### ISSUE TITLE
[Delete] Ability to delete order

### ISSUE THREAD

**Issue by rakshahegde10** [NYU-Devops-2022-Order/orders#12]
**As a** customer  
 **I need** a way to delete orders  
 **So that** customer can delete an order item from the orders list  
   
 ### Details and Assumptions
 * Users can delete an order
   
 ### Acceptance Criteria  
   
 ```gherkin
The orders collection list has all the orders '/orders/{id}/items'
When I delete an order
The order is removed from the orders collection ‘/orders’
 ```

**Comment by liubai01** [comment]
The endpoint is suggested to be `/orders/{order_id}` which removes items. `/orders/{order_id}/item/...` is reserved for editing item in the cart.

**Comment by qz701731tby** [comment]
[Bug Fix] Use db.relationship to connect Order and Item for cascade delete.
