### ISSUE TITLE
[Create] Ability to create order

### ISSUE THREAD

**Issue by rakshahegde10** [NYU-Devops-2022-Order/orders#4]
**As a** customer  
 **I need** a way to create orders  
 **So that** customer can add an order item to the orders list  
   
 ### Details and Assumptions
 * Users can add a new order
   
 ### Acceptance Criteria  
   
 ```gherkin
The orders collection list has all the orders '/orders'
When I create a new order
I get a new item in the order collection ‘/orders/{id}/items’
 ```

**Comment by VidishaShah29** [comment]
Recommend to separate this issue into two separate ones - 1. create 2. delete to cater to MVP

**Comment by VidishaShah29** [comment]
Recommend to separate this issue into two separate ones - 1. create 2. delete to cater to MVP

**Comment by VidishaShah29** [comment]
Recommend to separate this issue into two separate ones - 1. create 2. delete to cater to MVP

**Comment by VidishaShah29** [comment]
Recommend to separate this issue into two separate ones - 1. create 2. delete to cater to MVP

**Comment by VidishaShah29** [comment]
Recommend to separate this issue into two separate ones - 1. create 2. delete to cater to MVP

**Comment by liubai01** [comment]
According to Professor's suggestion, the endpoint is update to `POST /orders`. A json package is considered to use to convey data in details.
