### ISSUE TITLE
[Update] Update Order Request

### ISSUE THREAD

**Issue by tanmay2298** [NYU-Devops-2022-Order/orders#6]
**As a** Customer
**I need** the ability to update orders
**So that** customer can make changes to his order list

### Details and Assumptions
* Users can update an order
* Input format should point to which specific order needs to get updated

### Acceptance Criteria
```gherkin
When I update an order
I get to see my updated order in the order collection 'orders/{id}/items'
```

**Comment by liubai01** [comment]
Could refer to Professor's advice, be more specific:

```
POST   /orders/{id}/items       <- Add an item to an order
GET    /orders/{id}/items       <- List all items in an order
GET    /orders/{id}/items/{id}  <- Read an item from an order
PUT    /orders/{id}/items/{id}  <- Update an item in an order
DELETE /orders/{id}/items/{id}  <- Delete an item from an order
```
