### ISSUE TITLE
[Read] List orders for a target customer

### ISSUE THREAD

**Issue by qz701731tby** [NYU-Devops-2022-Order/orders#8]
**As a** customer, 
 **I need** check my both history order and current order, 
 **So that** I can rebuy something easily.
   
 ### Details and Assumptions
 * order should have a new field to clarify it is in progress or finished.
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given request `/paid_orders/{order_id}`
 When a customer would like to check the paid order in his buy records.
 Then return the list of paid orders.
 ```

**Comment by liubai01** [comment]
Refer to that [issue](https://github.com/NYU-Devops-2022-Order/orders/issues/2), I think they are doing actually the same kind of stuff.

**Comment by liubai01** [comment]
Add a {custom_id} to retrieve customer's identity
